import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { FiEdit3, FiTrash2 } from 'react-icons/fi';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { RecipeCardSkeleton } from '../components/loaders/RecipeCardSkeleton';
import { deleteRecipe, getMyRecipes } from '../services/recipe.service';
import { getErrorMessage } from '../utils/api-error';

export function ManageRecipesPage() {
 const [page,setPage]=useState(1); const client=useQueryClient();
 const query=useQuery({queryKey:['my-recipes',page],queryFn:()=>getMyRecipes(page)});
 const remove=useMutation({mutationFn:deleteRecipe,onSuccess:async()=>{toast.success('Recipe deleted');await Promise.all([client.invalidateQueries({queryKey:['my-recipes']}),client.invalidateQueries({queryKey:['dashboard']})]);},onError:(e)=>toast.error(getErrorMessage(e,'Recipe could not be deleted.'))});
 const confirmDelete=(id:string,title:string)=>{if(window.confirm(`Delete “${title}”? This cannot be undone.`))remove.mutate(id);};
 return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><header><p className="font-semibold uppercase tracking-widest text-primary">Your recipes</p><h1 className="mt-2 text-4xl font-bold text-neutral">Manage recipes</h1></header><Link className="btn btn-primary" to="/recipes/add"><FiEdit3/> Add recipe</Link></div>{query.isPending?<div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4},(_,i)=><RecipeCardSkeleton key={i}/>)}</div>:query.isError?<div className="alert alert-error mt-8">{getErrorMessage(query.error,'Your recipes could not be loaded.')}</div>:query.data.data.length===0?<div className="mt-10 rounded-card border border-dashed border-stone-300 p-12 text-center"><h2 className="text-xl font-bold">You have not added a recipe</h2><p className="mt-2 text-stone-500">Create a complete recipe and choose whether to publish it.</p><Link className="btn btn-primary mt-5" to="/recipes/add">Add your first recipe</Link></div>:<><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{query.data.data.map(recipe=><article key={recipe._id} className="flex overflow-hidden rounded-card border border-stone-200 bg-white shadow-soft sm:block"><img className="h-32 w-32 object-cover sm:h-44 sm:w-full" src={recipe.image} alt={`${recipe.title} recipe`}/><div className="flex min-w-0 flex-1 flex-col p-4"><div className="flex justify-between gap-2"><span className={`badge ${recipe.isPublished?'badge-success':'badge-ghost'}`}>{recipe.isPublished?'Published':'Draft'}</span><span className="text-xs text-stone-500">{recipe.category}</span></div><h2 className="mt-3 line-clamp-2 font-bold text-neutral">{recipe.title}</h2><div className="mt-auto flex gap-2 pt-4">{recipe.isPublished&&<Link className="btn btn-outline btn-sm flex-1" to={`/recipes/${recipe.slug}`}>View</Link>}<button className="btn btn-outline btn-sm border-red-300 text-red-700" disabled={remove.isPending} aria-label={`Delete ${recipe.title}`} onClick={()=>confirmDelete(recipe._id,recipe.title)}><FiTrash2/></button></div></div></article>)}</div>{query.data.meta.totalPages>1&&<div className="mt-8 flex justify-center gap-3"><button className="btn btn-outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span className="flex items-center text-sm">Page {page} of {query.data.meta.totalPages}</span><button className="btn btn-outline" disabled={page===query.data.meta.totalPages} onClick={()=>setPage(page+1)}>Next</button></div>}</>}</main>;
}
